Add example to DictType
It is unclear if `type` is (1) a Python `type` (2) a schematics type defined in `schematics.types`. Adding an example clarifies which is which to avoid exceptions such as `AttributeError: 'str' object has no attribute 'owner_model'`.